### ISSUE TITLE
Battery reports [not a issue per say]

### ISSUE THREAD

**Issue by 16-Bit-Dog** [Ohjurot/DualSense-Windows#10]
(I don't own a dual sense controller to test, so i'll just put this here in case the research helps - I include it since you listed battery info polling as a future step)

https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/get-battery-info

^ essentially, win api's document lists a example on a way to fetch and update battery info

**Comment by Ohjurot** [comment]
@16-Bit-Dog Thank you! I will take a look at it. Let's hope that the DualSense controller plays nice with battery info. I actually think that [https://docs.microsoft.com/en-us/windows/win32/power/battery-information](https://docs.microsoft.com/en-us/windows/win32/power/battery-information) will play more nicely with the API because UWP is a nightmare to integrate into non UWP projects...
Probably the UWP function will call the DeviceIoControl function internally.
