### ISSUE TITLE
BT gyro info reading with another program

### ISSUE THREAD

**Issue by LeifMessinger** [Ohjurot/DualSense-Windows#3]
There was a link from the other issue's form, it had a link to some other software.
[Darn link didn't show up](https://beta.inputmapper.com/product/hid-report-listener/)
I think the "Input reports" correspond to the 78 bytes in the buffer.
0-9 seems to be the same as what we get
11 is 1 when the ps button is clicked
11 is 2 when the touchpad is clicked
11 is 4 (third bit) when the mute button is clicked
17-28 seem to be the gyro
34-37 seem to be the touchpad
39-41 seem to be the second finger on the touchpad
38 and 42 are wildin, but seem to be connected to the touchpad data
52 counts up each poll, then overflows to 53, which I assume overflows to 54,55, and 56
29 to 32 seem to be more precise time, note how 52-53 and 31-32 are the same thing

Considering that "Headphones connected" is a single bit out of 78 bytes, that's basically a needle in a haystack. The only question is why does this program get more detailed info than this one...

**Comment by LeifMessinger** [comment]
The headphones seem to be another HID Device, 

![image](https://user-images.githubusercontent.com/59458630/99179375-b9680b00-26e2-11eb-90b9-7ece6176932b.png)

**Comment by LeifMessinger** [comment]
Only thing left to find is the mic, adaptive triggers, leds, and battery state.

**Comment by describe19** [comment]
https://github.com/Ryochan7/DS4Windows/commits/dualsense-integration
Ryochan has put battery in his dualsense branch now. He has a discord if you want to contact him, it's linked in the ds4windows readme.

**Comment by Ohjurot** [comment]
@LeifMessinger 
I will check out the other software and the issue thread. My suspicion is that you have to first send a „controller enable“ and than you can read all input data. 
The adaptive triggers are actually special speakers so that may be the other hid device. 
However it is also possible to Control the adaptive triggers via the default output report (Sony has a few fixed features with only a few parameters available)
The main speaker and the headphone jack seems to be detected by windows as normal speakers, so there is no need for specific integration (however I have not testet it yet). Same should go for the mic. But still some research to do.

My current plans are:
- Pushing my research in writing to the controller to the repo (I can control everything via USB no problem... Bluetooth is a different story)
- Connecting with the DS4Windows people and try figuring out how to use full functionality over Bluetooth
- Writing more complex haptic featured for the triggers „speaker mode“

**Comment by Ohjurot** [comment]
@describe19 Thanks! I will get to that later this day.

**Comment by describe19** [comment]
I'm very thankful for the work being done on this so quickly great job.

**Comment by FancyBanana** [comment]
@Ohjurot I think you're confusing haptic feedback (which is sees as rear 2 channel audio) and adaptive triggers.

**Comment by Ohjurot** [comment]
@FancyBanana you are right! I always thought that the rumble motors and the adaptive triggers are the haptic feedback. Just discovered this functionality. I just tested it out like it was done in this [Video](https://www.youtube.com/watch?v=EzqaclFn_Q4) and it works amazingly well. So, another point on my to do list... This controller is getting better and better ;)

**Comment by Ohjurot** [comment]
BT is done
