### ISSUE TITLE
Left rumble is much more intense than right rumble

### ISSUE THREAD

**Issue by describe19** [Ohjurot/DualSense-Windows#5]
There's quite a difference between setting outstate.leftRumble = 0xFF and outstate.rightRumble = 0xFF. The left one is much deeper and more intense.

Using USB connection.

edit: The vibration frequencies are about an octave apart, left is B1 and right B2.

**Comment by Ohjurot** [comment]
I have just commented on the DS4 Issue, but I will copy paste you my answer here as well:

@describe19 As far as I know they are supposed to produce a different intensity of rumble (The left on is the hard rumble, the right one the soft). I think to get the compatibility for older games so that you don’t need to produce real haptic packages
.
Also, when you look at other types of controllers like the old DS4 or the XBox controller, they all have the two different rumble types... So, I think Sony did that for compatibility reasons. So they simulate rumbles when you don’t want to use the haptic feedback.
